# Git Version Control

## Guides and Links

+ [git - the simple guide](http://rogerdudler.github.io/git-guide/)
+ [RStudioVersion control](https://support.rstudio.com/hc/en-us/articles/200532077-Version-Control-with-Git-and-SVN)
+ [Pro Git book](http://git-scm.com/book)
+ [Standford Git guide](http://www-cs-students.stanford.edu/~blynn/gitmagic/)
+ [Aha! Moments When Learning Git](http://betterexplained.com/articles/aha-moments-when-learning-git/)
+ [git branching](http://learngitbranching.js.org/)
+ http://ohshitgit.com/
+ [Karl Broman](https://kbroman.org/github_tutorial/)
+ [Happy git with R - Jenny Bryan](Jenny Bryan)
+ [Github Guides](https://guides.github.com/)

## Setup 

Setting global name and email in terminal:

```
git config --global user.name "james edwards"
git config --global user.email jamese1326@gmail.com
```

## Undoing

To undo a commit before it has been pushed see [here](https://bytefreaks.net/programming-2/how-to-undo-a-git-commit-that-was-not-pushed). Replace "~HEAD;" with "origin/master". So, normally I will need:
```
git reset origin/master
```

More on this:

https://blog.github.com/2015-06-08-how-to-undo-almost-anything-with-git/
https://stackoverflow.com/questions/927358/how-to-undo-the-most-recent-commits-in-git?rq=1

## Github Collaboration

I haven't had a lot of collaborative work. 

The easiest way to work freely on a project is for the repo owner to add me as a collaborator on GitHub. I can then clone and push to the project as though it is my own. The URL is remains as it was originally (i.e. still on the owner's github). This URL is used for cloning and setting up a project in RStudio, but it will be listed in my projects on github.

If I am not a collaborator then I can fork the project into my github (create a copy), which I can then clone. To push changes to the original project I have to create a pull request (request that Rhian pulls the changes), which will be added to the main project if Rhian accepts the changes. The pull request is performed on Rhian’s github page. I think I followed this guide to [collaborating on projects with git](https://github.com/codepath/android_guides/wiki/Collaborating-on-Projects-with-Git). More on forking [here](https://stackoverflow.com/questions/3611256/forking-vs-branching-in-github) and [here](https://stackoverflow.com/questions/6286571/are-git-forks-actually-git-clones) (the second thread says forks aren’t a command in git but a higher level concept – cloning is the corresponding git action). There is an [introduction to git and Rstudio](http://r-bio.github.io/intro-git-rstudio/).

## Git and Latex

[Git and LaTeX Workflow ](https://stackoverflow.com/questions/6188780/git-latex-workflow). Has some interesting comments on how to use Git effectively with LaTeX that might be relevant to version control with other documents.