---
title: "testthat Notes"
output: html_document
---

Notes from 2018 (or earlier) so may not all be relevant now. See also [chapter in R packages book](http://r-pkgs.had.co.nz/tests.html).

This is a Hadley Wickham package designed to make testing easier. I found it worked well. There is a good introductory article at http://journal.r-project.org/archive/2011-1/RJournal_2011-1_Wickham.pdf. The notes here compliment that.

I kept a separate folder for test files. Each of these should be named starting with test. You can run multiple tests within each file and on different functions. I am not sure how these should be split for the best. Ideally each file would have a fairly tight focus but I combined several areas into the same file because I had to initalise the same variables for many of the different tests and it seemed neater to not do this too often.

Each test file starts with a `context("some text")` which will be displayed when the tests are run. It should be something that applies to all the tests in that file. Within the file are `test_that()` function calls such as:

```
test_that("actGreedy gives correct actions", {
  ...tests go here...
})
```

Multiple tests using `expect_that()` functions are put in the brackets. The text argument will be displayed when a test in this function fails. If a test fails then no further tests within that `test_that()` call are made. Any variables set inside a `test_that()` function call are local.

Test files can be run individually with e.g. `test_file("test_policies.R")` but more normal will be to run all tests within a folder e.g. `test_dir("tests/")`. This will run all files starting with "test..." in that folder.

When using test_dir(path) the working directory (wd) is set to the argument "path" for the duration of the test. I can change the wd within test files but after the file is finished the wd goes back to "path" and after all tests are finished the wd goes back to what it was before the `test_dir()` call.

I used a separate (short) file for the code to run the tests (load testthat, source functions, run test_dir). Kept in the main project folder.

Some tests compared output to a saved object. This doesn't really test the function but it does test that output is unchanged is I later change the function. I kept these objects in a separate folder "test_data" and had a file which creates the data in the main project folder.

## Variable domains

I had a problem with one test for a reason I don't fully understand. The setup was the following:

```
context("myContext")
myVar <- 1

test_that("blah"){
  function that needs myVar but does not have it as an argument
}
```

This will fail as `myVar` is not found. However, if myVar has been declared outside of the test (in the normal workspace) then it is fine. It is also fine if myVar is given as an argument. If I check `exists(myVar)` inside the test then it returns TRUE.

Any variables set inside a test_that() function call are local. When using `test_dir(path)` the working directory (wd) is set to the argument "path for the duration of the test. I can change the wd within test files but after the file is finished the wd goes back to "path" and after all tests are finished the wd goes back to what it was before the `test_dir()` call.

## Good Practice

The testthat package gives a way to test but the more difficult question is what tests to use. What are good or bad test?

http://blog.stevensanderson.com/2009/08/24/writing-great-unit-tests-best-and-worst-practises/. This says that unit testing is *not* about finding bugs (more usefully done through integration tests) but more about documenting design - specifying the software's behaviour. Some of the comments disagree though.

## Misc

[Testing R Code book review](https://pdfs.semanticscholar.org/7459/e9a0ede1f16679ba3058218a7e4b304f4450.pdf)

## Runtime testing 

[assertive](https://github.com/cran/assertive) is featured in the *Testing R Code* book. On the github page it links to five other packages:

+ Tony Fishettti's [assertr](https://github.com/ropensci/assertr)
+ Hadley Wickham's [assertthat](https://github.com/hadley/assertthat). Not updated in 2 years. Not used in most of the tidyverse packages. I think tidyverse uses internal functions.
+ Michel Lang's [checkmate](https://mllg.github.io/checkmate/)
+ Stefan Bache's [ensurer](https://github.com/smbache/ensurer)
+ Gaston Sanchez's [tester](https://github.com/gastonstat/tester). Quite old and not heavily developed.

I've also considered [chk](https://poissonconsulting.github.io/chk/index.html) which says it is for checking user supplied arguments.
